name: Test Project
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello
        uses: echo "Hello"
      # - name: Pull Code
      #   uses: actions/checkout@v4@main
      # - name: Install NodeJS
      #   uses: actions/setup-node@v4
      #   with:
      #     node-version: 18
      # - name: Install dependencies
      #   uses: npm ci
      # - name: Run Tests
      #   uses: npm test
